/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings worker/bindings.d.ts` (hash: d383d847879f3d4aaa8cb0ee5f0db90b)
interface __BaseEnv_CloudflareBindings {
	FILES: R2Bucket;
	ASSETS: Fetcher;
	UPLOAD_AUTH_MODE: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_REDIRECT_URI: string;
	GOOGLE_ALLOWED_EMAILS: string;
	UPLOAD_PASSWORD_REQUIRED: string;
	DEFAULT_TTL_SECONDS: string;
	MAX_TTL_SECONDS: string;
	DEFAULT_DOWNLOADS: string;
	MAX_DOWNLOADS: string;
	MAX_STORED_BYTES: string;
	MAX_ACTIVE_FILES: string;
	MAX_UPLOADS_PER_DAY: string;
	MAX_DOWNLOADS_PER_DAY: string;
	MAX_DOWNLOADS_PER_MONTH: string;
	MAX_R2_CLASS_A_PER_DAY: string;
	MAX_R2_CLASS_A_PER_MONTH: string;
	MAX_R2_CLASS_B_PER_DAY: string;
	MAX_R2_CLASS_B_PER_MONTH: string;
	MAX_PART_ATTEMPTS: string;
	MAX_COMPLETE_ATTEMPTS: string;
	APP_SECRET: string;
	UPLOAD_PASSWORD: string;
	STATE: DurableObjectNamespace<import("./index").DropState>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "DropState";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "UPLOAD_AUTH_MODE" | "GOOGLE_CLIENT_ID" | "GOOGLE_REDIRECT_URI" | "GOOGLE_ALLOWED_EMAILS" | "UPLOAD_PASSWORD_REQUIRED" | "DEFAULT_TTL_SECONDS" | "MAX_TTL_SECONDS" | "DEFAULT_DOWNLOADS" | "MAX_DOWNLOADS" | "MAX_STORED_BYTES" | "MAX_ACTIVE_FILES" | "MAX_UPLOADS_PER_DAY" | "MAX_DOWNLOADS_PER_DAY" | "MAX_DOWNLOADS_PER_MONTH" | "MAX_R2_CLASS_A_PER_DAY" | "MAX_R2_CLASS_A_PER_MONTH" | "MAX_R2_CLASS_B_PER_DAY" | "MAX_R2_CLASS_B_PER_MONTH" | "MAX_PART_ATTEMPTS" | "MAX_COMPLETE_ATTEMPTS" | "APP_SECRET" | "UPLOAD_PASSWORD">> {}
}
